if(NOT TARGET OCKThirdParty::cli11)
  message(FATAL_ERROR "ock CLI requires the locked CLI dependency component")
endif()
add_executable(ock main.cpp)
target_link_libraries(ock PRIVATE OCK::ControlClient OCK::Adapter::LocalIPC)
target_link_options(ock PRIVATE /MAP)
target_include_directories(ock SYSTEM PRIVATE "$<TARGET_PROPERTY:ock_dep_cli11,INTERFACE_INCLUDE_DIRECTORIES>")
target_compile_definitions(ock PRIVATE "$<TARGET_PROPERTY:ock_dep_cli11,INTERFACE_COMPILE_DEFINITIONS>")
install(TARGETS ock RUNTIME DESTINATION bin)
