add_executable(ock_settings_service main.cpp)
target_link_libraries(ock_settings_service PRIVATE OCK::State OCK::Runtime)
if(OCK_BUILD_CPU_POOL)
  target_link_libraries(ock_settings_service PRIVATE OCK::Adapter::CpuPool)
  target_compile_definitions(ock_settings_service PRIVATE OCK_SETTINGS_MANAGED=1)
endif()
target_compile_features(ock_settings_service PRIVATE cxx_std_20)
