cmake_minimum_required(VERSION 3.25)
project(NativeCompileContract LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_library(positive OBJECT EXCLUDE_FROM_ALL positive.cpp)
target_compile_options(positive PRIVATE /EHsc /utf-8 /Zc:__cplusplus /permissive-)
target_include_directories(positive PRIVATE [==[E:/VS2019Qt5.15/3D]==] [==[E:/VS2019Qt5.15/3D/packages/contracts/include]==] [==[E:/VS2019Qt5.15/3D/packages/foundation/include]==] [==[E:/VS2019Qt5.15/3D/build/d0.06-a/cache/sources/expected-fe3b18aecb84/include]==])
add_library(block OBJECT EXCLUDE_FROM_ALL block.cpp)
target_compile_options(block PRIVATE /EHsc /utf-8 /Zc:__cplusplus /permissive-)
target_include_directories(block PRIVATE [==[E:/VS2019Qt5.15/3D]==] [==[E:/VS2019Qt5.15/3D/packages/contracts/include]==] [==[E:/VS2019Qt5.15/3D/packages/foundation/include]==] [==[E:/VS2019Qt5.15/3D/build/d0.06-a/cache/sources/expected-fe3b18aecb84/include]==])
add_library(wait OBJECT EXCLUDE_FROM_ALL wait.cpp)
target_compile_options(wait PRIVATE /EHsc /utf-8 /Zc:__cplusplus /permissive-)
target_include_directories(wait PRIVATE [==[E:/VS2019Qt5.15/3D]==] [==[E:/VS2019Qt5.15/3D/packages/contracts/include]==] [==[E:/VS2019Qt5.15/3D/packages/foundation/include]==] [==[E:/VS2019Qt5.15/3D/build/d0.06-a/cache/sources/expected-fe3b18aecb84/include]==])
add_library(force_inline OBJECT EXCLUDE_FROM_ALL force_inline.cpp)
target_compile_options(force_inline PRIVATE /EHsc /utf-8 /Zc:__cplusplus /permissive-)
target_include_directories(force_inline PRIVATE [==[E:/VS2019Qt5.15/3D]==] [==[E:/VS2019Qt5.15/3D/packages/contracts/include]==] [==[E:/VS2019Qt5.15/3D/packages/foundation/include]==] [==[E:/VS2019Qt5.15/3D/build/d0.06-a/cache/sources/expected-fe3b18aecb84/include]==])
add_library(force_inline_call OBJECT EXCLUDE_FROM_ALL force_inline_call.cpp)
target_compile_options(force_inline_call PRIVATE /EHsc /utf-8 /Zc:__cplusplus /permissive-)
target_include_directories(force_inline_call PRIVATE [==[E:/VS2019Qt5.15/3D]==] [==[E:/VS2019Qt5.15/3D/packages/contracts/include]==] [==[E:/VS2019Qt5.15/3D/packages/foundation/include]==] [==[E:/VS2019Qt5.15/3D/build/d0.06-a/cache/sources/expected-fe3b18aecb84/include]==])
