# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 3.0.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "3.0.0")
   message(FATAL_ERROR "CMake >= 3.0.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 3.0.0...3.29)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS OCK::Foundation OCK::CoreContracts OCK::Runtime OCK::Data OCK::Dynamic OCK::Automation OCK::State OCK::Workspace OCK::Durable OCK::StateDurable OCK::DurablePlan OCK::ControlProtocol OCK::Control OCK::ControlClient OCK::Adapter::CpuPool OCK::Adapter::Logging OCK::Adapter::Config OCK::Adapter::SQLite OCK::Adapter::Storage OCK::Adapter::LocalIPC OCK::Adapter::MCP)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target OCK::Foundation
add_library(OCK::Foundation INTERFACE IMPORTED)

set_target_properties(OCK::Foundation PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_20"
  INTERFACE_COMPILE_OPTIONS "\$<\$<CXX_COMPILER_ID:MSVC>:/utf-8>;\$<\$<CXX_COMPILER_ID:MSVC>:/EHsc>;\$<\$<CXX_COMPILER_ID:MSVC>:/Zc:__cplusplus>;\$<\$<CXX_COMPILER_ID:MSVC>:/permissive->"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "OCKThirdParty::expected"
  OCK_IMPLEMENTATION_STAGE "Implemented"
)

# Create imported target OCK::CoreContracts
add_library(OCK::CoreContracts INTERFACE IMPORTED)

set_target_properties(OCK::CoreContracts PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_20"
  INTERFACE_COMPILE_OPTIONS "\$<\$<CXX_COMPILER_ID:MSVC>:/utf-8>"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "OCK::Foundation"
  OCK_IMPLEMENTATION_STAGE "Implemented"
)

# Create imported target OCK::Runtime
add_library(OCK::Runtime STATIC IMPORTED)

set_target_properties(OCK::Runtime PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_20"
  INTERFACE_COMPILE_OPTIONS "\$<\$<CXX_COMPILER_ID:MSVC>:/utf-8>"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "OCK::CoreContracts;\$<LINK_ONLY:bcrypt>"
  OCK_IMPLEMENTATION_STAGE "NativeSubset"
)

# Create imported target OCK::Data
add_library(OCK::Data INTERFACE IMPORTED)

set_target_properties(OCK::Data PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_20"
  INTERFACE_COMPILE_OPTIONS "\$<\$<CXX_COMPILER_ID:MSVC>:/utf-8>"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "OCK::Foundation"
  OCK_IMPLEMENTATION_STAGE "ContractBaseline"
)

# Create imported target OCK::Dynamic
add_library(OCK::Dynamic INTERFACE IMPORTED)

set_target_properties(OCK::Dynamic PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_20"
  INTERFACE_COMPILE_OPTIONS "\$<\$<CXX_COMPILER_ID:MSVC>:/utf-8>"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "OCK::Runtime;OCK::Data"
  OCK_IMPLEMENTATION_STAGE "ContractBaseline"
)

# Create imported target OCK::Automation
add_library(OCK::Automation INTERFACE IMPORTED)

set_target_properties(OCK::Automation PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_20"
  INTERFACE_COMPILE_OPTIONS "\$<\$<CXX_COMPILER_ID:MSVC>:/utf-8>"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "OCK::Runtime;OCK::Dynamic"
  OCK_IMPLEMENTATION_STAGE "ContractBaseline"
)

# Create imported target OCK::State
add_library(OCK::State INTERFACE IMPORTED)

set_target_properties(OCK::State PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_20"
  INTERFACE_COMPILE_OPTIONS "\$<\$<CXX_COMPILER_ID:MSVC>:/utf-8>"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "OCK::CoreContracts"
  OCK_IMPLEMENTATION_STAGE "ContractBaseline"
)

# Create imported target OCK::Workspace
add_library(OCK::Workspace INTERFACE IMPORTED)

set_target_properties(OCK::Workspace PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_20"
  INTERFACE_COMPILE_OPTIONS "\$<\$<CXX_COMPILER_ID:MSVC>:/utf-8>"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "OCK::State"
  OCK_IMPLEMENTATION_STAGE "ContractBaseline"
)

# Create imported target OCK::Durable
add_library(OCK::Durable INTERFACE IMPORTED)

set_target_properties(OCK::Durable PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_20"
  INTERFACE_COMPILE_OPTIONS "\$<\$<CXX_COMPILER_ID:MSVC>:/utf-8>"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "OCK::CoreContracts"
  OCK_IMPLEMENTATION_STAGE "ContractBaseline"
)

# Create imported target OCK::StateDurable
add_library(OCK::StateDurable INTERFACE IMPORTED)

set_target_properties(OCK::StateDurable PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_20"
  INTERFACE_COMPILE_OPTIONS "\$<\$<CXX_COMPILER_ID:MSVC>:/utf-8>"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "OCK::State;OCK::Durable"
  OCK_IMPLEMENTATION_STAGE "ContractBaseline"
)

# Create imported target OCK::DurablePlan
add_library(OCK::DurablePlan INTERFACE IMPORTED)

set_target_properties(OCK::DurablePlan PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_20"
  INTERFACE_COMPILE_OPTIONS "\$<\$<CXX_COMPILER_ID:MSVC>:/utf-8>"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "OCK::Automation;OCK::Durable"
  OCK_IMPLEMENTATION_STAGE "ContractBaseline"
)

# Create imported target OCK::ControlProtocol
add_library(OCK::ControlProtocol INTERFACE IMPORTED)

set_target_properties(OCK::ControlProtocol PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_20"
  INTERFACE_COMPILE_OPTIONS "\$<\$<CXX_COMPILER_ID:MSVC>:/utf-8>"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "OCK::CoreContracts;OCK::Data"
  OCK_IMPLEMENTATION_STAGE "ContractBaseline"
)

# Create imported target OCK::Control
add_library(OCK::Control INTERFACE IMPORTED)

set_target_properties(OCK::Control PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_20"
  INTERFACE_COMPILE_OPTIONS "\$<\$<CXX_COMPILER_ID:MSVC>:/utf-8>"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "OCK::Runtime;OCK::Dynamic;OCK::ControlProtocol"
  OCK_IMPLEMENTATION_STAGE "ContractBaseline"
)

# Create imported target OCK::ControlClient
add_library(OCK::ControlClient INTERFACE IMPORTED)

set_target_properties(OCK::ControlClient PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_20"
  INTERFACE_COMPILE_OPTIONS "\$<\$<CXX_COMPILER_ID:MSVC>:/utf-8>"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "OCK::ControlProtocol"
  OCK_IMPLEMENTATION_STAGE "ContractBaseline"
)

# Create imported target OCK::Adapter::CpuPool
add_library(OCK::Adapter::CpuPool INTERFACE IMPORTED)

set_target_properties(OCK::Adapter::CpuPool PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_20"
  INTERFACE_COMPILE_OPTIONS "\$<\$<CXX_COMPILER_ID:MSVC>:/utf-8>"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "OCK::CoreContracts"
  OCK_IMPLEMENTATION_STAGE "ContractBaseline"
)

# Create imported target OCK::Adapter::Logging
add_library(OCK::Adapter::Logging INTERFACE IMPORTED)

set_target_properties(OCK::Adapter::Logging PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_20"
  INTERFACE_COMPILE_OPTIONS "\$<\$<CXX_COMPILER_ID:MSVC>:/utf-8>"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "OCK::CoreContracts"
  OCK_IMPLEMENTATION_STAGE "ContractBaseline"
)

# Create imported target OCK::Adapter::Config
add_library(OCK::Adapter::Config INTERFACE IMPORTED)

set_target_properties(OCK::Adapter::Config PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_20"
  INTERFACE_COMPILE_OPTIONS "\$<\$<CXX_COMPILER_ID:MSVC>:/utf-8>"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "OCK::Dynamic"
  OCK_IMPLEMENTATION_STAGE "ContractBaseline"
)

# Create imported target OCK::Adapter::SQLite
add_library(OCK::Adapter::SQLite INTERFACE IMPORTED)

set_target_properties(OCK::Adapter::SQLite PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_20"
  INTERFACE_COMPILE_OPTIONS "\$<\$<CXX_COMPILER_ID:MSVC>:/utf-8>"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "OCK::Durable"
  OCK_IMPLEMENTATION_STAGE "ContractBaseline"
)

# Create imported target OCK::Adapter::Storage
add_library(OCK::Adapter::Storage INTERFACE IMPORTED)

set_target_properties(OCK::Adapter::Storage PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_20"
  INTERFACE_COMPILE_OPTIONS "\$<\$<CXX_COMPILER_ID:MSVC>:/utf-8>"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "OCK::CoreContracts"
  OCK_IMPLEMENTATION_STAGE "ContractBaseline"
)

# Create imported target OCK::Adapter::LocalIPC
add_library(OCK::Adapter::LocalIPC INTERFACE IMPORTED)

set_target_properties(OCK::Adapter::LocalIPC PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_20"
  INTERFACE_COMPILE_OPTIONS "\$<\$<CXX_COMPILER_ID:MSVC>:/utf-8>"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "OCK::ControlProtocol"
  OCK_IMPLEMENTATION_STAGE "ContractBaseline"
)

# Create imported target OCK::Adapter::MCP
add_library(OCK::Adapter::MCP INTERFACE IMPORTED)

set_target_properties(OCK::Adapter::MCP PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_20"
  INTERFACE_COMPILE_OPTIONS "\$<\$<CXX_COMPILER_ID:MSVC>:/utf-8>"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "OCK::Control"
  OCK_IMPLEMENTATION_STAGE "ContractBaseline"
)

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/OCKTargets-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  if(CMAKE_VERSION VERSION_LESS "3.28"
      OR NOT DEFINED _cmake_import_check_xcframework_for_${_cmake_target}
      OR NOT IS_DIRECTORY "${_cmake_import_check_xcframework_for_${_cmake_target}}")
    foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
      if(NOT EXISTS "${_cmake_file}")
        message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
      endif()
    endforeach()
  endif()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# Make sure the targets which have been exported in some other
# export set exist.
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
foreach(_target "OCKThirdParty::expected" )
  if(NOT TARGET "${_target}" )
    set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets "${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets} ${_target}")
  endif()
endforeach()

if(DEFINED ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
  if(CMAKE_FIND_PACKAGE_NAME)
    set( ${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
    set( ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  else()
    message(FATAL_ERROR "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  endif()
endif()
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
