# D0.06-a：按组件取得锁定依赖；只供本包探针及后续显式集成使用。
include_guard(GLOBAL)
get_filename_component(OCK_DEPENDENCY_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
if(NOT MSVC OR NOT WIN32 OR NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
  message(FATAL_ERROR "D0.06-a currently supports only verified Windows MSVC x64")
endif()
set(CMAKE_MSVC_DEBUG_INFORMATION_FORMAT "Embedded")
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>DLL")
set(OCK_DEPENDENCY_COMPONENTS "Embedded" CACHE STRING "Explicit dependency component selection")
set(OCK_DEPENDENCY_CACHE "${CMAKE_BINARY_DIR}/_locked_dependencies" CACHE PATH "Locked archive/source cache; can be preprovided offline")
option(OCK_DEPENDENCIES_OFFLINE "Refuse all dependency network downloads" OFF)
option(OCK_ENABLE_ASAN "Enable the locally probed MSVC AddressSanitizer configuration" OFF)
find_package(Python3 3.11 REQUIRED COMPONENTS Interpreter)
set(_offline_arg "")
if(OCK_DEPENDENCIES_OFFLINE)
  set(_offline_arg --offline)
endif()
execute_process(COMMAND "${Python3_EXECUTABLE}" -X utf8 "${OCK_DEPENDENCY_ROOT}/tools/dependencies/prepare.py"
  --lock "${OCK_DEPENDENCY_ROOT}/dependencies.lock" --components "${OCK_DEPENDENCY_COMPONENTS}"
  --cache "${OCK_DEPENDENCY_CACHE}" ${_offline_arg} --output "${CMAKE_BINARY_DIR}/dependency-acquisition.json"
  RESULT_VARIABLE _dependency_result OUTPUT_VARIABLE _dependency_stdout ERROR_VARIABLE _dependency_stderr)
if(NOT _dependency_result EQUAL 0)
  message(FATAL_ERROR "Locked dependency preparation failed: ${_dependency_stdout}
${_dependency_stderr}")
endif()
include("${CMAKE_BINARY_DIR}/dependency-acquisition.cmake")
file(READ "${OCK_DEPENDENCY_ROOT}/dependencies.lock" _ock_lock)
foreach(_field compiler_version cmake_version windows_sdk)
  string(JSON _locked_${_field} GET "${_ock_lock}" toolchain "${_field}")
endforeach()
if(NOT CMAKE_CXX_COMPILER_VERSION STREQUAL _locked_compiler_version OR NOT CMAKE_VERSION STREQUAL _locked_cmake_version OR NOT CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION STREQUAL _locked_windows_sdk)
  message(FATAL_ERROR "Actual compiler/CMake/SDK differs from the reviewed dependency toolchain")
endif()
if("sqlite" IN_LIST OCK_SELECTED_DEPENDENCIES)
  enable_language(C)
endif()
foreach(_name IN LISTS OCK_SELECTED_DEPENDENCIES)
  string(JSON _count LENGTH "${_ock_lock}" dependencies "${_name}" cmake_options)
  if(_count GREATER 0)
    math(EXPR _last "${_count}-1")
    foreach(_index RANGE 0 ${_last})
      string(JSON _key MEMBER "${_ock_lock}" dependencies "${_name}" cmake_options ${_index})
      string(JSON _value GET "${_ock_lock}" dependencies "${_name}" cmake_options "${_key}")
      set(${_key} "${_value}" CACHE BOOL "Fixed by dependencies.lock" FORCE)
    endforeach()
  endif()
endforeach()
if(OCK_ENABLE_ASAN)
  string(REGEX REPLACE "/RTC[1su]" "" CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG}")
  string(REGEX REPLACE "/RTC[1su]" "" CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG}")
  add_compile_options(/fsanitize=address)
  add_link_options(/INCREMENTAL:NO)
endif()
add_compile_options("$<$<COMPILE_LANGUAGE:CXX>:/utf-8>" "$<$<COMPILE_LANGUAGE:CXX>:/Zc:__cplusplus>" "$<$<COMPILE_LANGUAGE:CXX>:/permissive->" "$<$<COMPILE_LANGUAGE:CXX>:/EHsc>")
function(ock_dependency_definitions target name visibility)
  string(JSON _count LENGTH "${_ock_lock}" dependencies "${name}" compile_definitions)
  if(_count GREATER 0)
    math(EXPR _last "${_count}-1")
    foreach(_index RANGE 0 ${_last})
      string(JSON _key MEMBER "${_ock_lock}" dependencies "${name}" compile_definitions ${_index})
      string(JSON _value GET "${_ock_lock}" dependencies "${name}" compile_definitions "${_key}")
      target_compile_definitions(${target} ${visibility} "${_key}=${_value}")
    endforeach()
  endif()
endfunction()
function(ock_dependency_header name directory)
  if(NOT name IN_LIST OCK_SELECTED_DEPENDENCIES)
    return()
  endif()
  add_library(ock_dep_${name} INTERFACE)
  add_library(OCKThirdParty::${name} ALIAS ock_dep_${name})
  target_include_directories(ock_dep_${name} SYSTEM INTERFACE "${OCK_DEP_${name}_SOURCE}/${directory}")
  target_compile_features(ock_dep_${name} INTERFACE cxx_std_20)
  ock_dependency_definitions(ock_dep_${name} ${name} INTERFACE)
endfunction()
ock_dependency_header(expected include)
ock_dependency_header(jsoncons include)
ock_dependency_header(thread_pool include)
ock_dependency_header(asio asio/include)
ock_dependency_header(immer .)
ock_dependency_header(toml11 include)
ock_dependency_header(cli11 include)
if("fmt" IN_LIST OCK_SELECTED_DEPENDENCIES)
  add_subdirectory("${OCK_DEP_fmt_SOURCE}" "${CMAKE_BINARY_DIR}/_upstream/fmt" EXCLUDE_FROM_ALL)
  add_library(OCKThirdParty::fmt ALIAS fmt)
endif()
if("spdlog" IN_LIST OCK_SELECTED_DEPENDENCIES)
  add_subdirectory("${OCK_DEP_spdlog_SOURCE}" "${CMAKE_BINARY_DIR}/_upstream/spdlog" EXCLUDE_FROM_ALL)
  add_library(OCKThirdParty::spdlog ALIAS spdlog)
endif()
if("sqlite" IN_LIST OCK_SELECTED_DEPENDENCIES)
  add_library(ock_dep_sqlite STATIC "${OCK_DEP_sqlite_SOURCE}/sqlite3.c")
  add_library(OCKThirdParty::sqlite ALIAS ock_dep_sqlite)
  target_include_directories(ock_dep_sqlite SYSTEM PUBLIC "${OCK_DEP_sqlite_SOURCE}")
  ock_dependency_definitions(ock_dep_sqlite sqlite PUBLIC)
endif()
if("catch2" IN_LIST OCK_SELECTED_DEPENDENCIES)
  add_library(ock_dep_catch2 STATIC "${OCK_DEP_catch2_SOURCE}/extras/catch_amalgamated.cpp")
  add_library(OCKThirdParty::catch2 ALIAS ock_dep_catch2)
  target_include_directories(ock_dep_catch2 SYSTEM PUBLIC "${OCK_DEP_catch2_SOURCE}/extras")
  target_compile_options(ock_dep_catch2 PRIVATE /bigobj)
endif()
if("benchmark" IN_LIST OCK_SELECTED_DEPENDENCIES)
  add_subdirectory("${OCK_DEP_benchmark_SOURCE}" "${CMAKE_BINARY_DIR}/_upstream/benchmark" EXCLUDE_FROM_ALL)
  add_library(OCKThirdParty::benchmark ALIAS benchmark)
endif()
