# 内核受控验证专用：在 project()/编译器识别之前隔离用户级构建注入。
# 使用本文件位置，确保 try_compile 子工程定位一致。
if(NOT CMAKE_GENERATOR MATCHES "^Visual Studio ")
  message(FATAL_ERROR "LockedMSVC requires the reviewed Visual Studio generator")
endif()
set(_ock_isolated_globals "")
foreach(_ock_global IN LISTS CMAKE_VS_GLOBALS)
  string(TOLOWER "${_ock_global}" _ock_global_lower)
  if(NOT _ock_global_lower MATCHES "^(vcpkgenabled|userrootdir)=")
    list(APPEND _ock_isolated_globals "${_ock_global}")
  endif()
endforeach()
list(APPEND _ock_isolated_globals "VcpkgEnabled=false" "UserRootDir=${CMAKE_CURRENT_LIST_DIR}/msbuild-user/")
set(CMAKE_VS_GLOBALS "${_ock_isolated_globals}")
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES CMAKE_VS_GLOBALS)
list(REMOVE_DUPLICATES CMAKE_TRY_COMPILE_PLATFORM_VARIABLES)
unset(_ock_isolated_globals)
unset(_ock_global)
unset(_ock_global_lower)
