# 安装元数据投影来自唯一 API 清单，不维护第二套头/目标名单。
file(READ "${PROJECT_SOURCE_DIR}/sdk/sdk_api_manifest.json" _ock_installed_manifest)
get_property(_ock_installed_targets GLOBAL PROPERTY OCK_CONTRACT_TARGETS)
string(JSON _ock_target_count LENGTH "${_ock_installed_manifest}" targets)
math(EXPR _ock_target_last "${_ock_target_count}-1")
foreach(_ock_index RANGE ${_ock_target_last} 0 -1)
  string(JSON _ock_name MEMBER "${_ock_installed_manifest}" targets ${_ock_index})
  if(NOT _ock_name IN_LIST _ock_installed_targets)
    string(JSON _ock_installed_manifest REMOVE "${_ock_installed_manifest}" targets "${_ock_name}")
  endif()
endforeach()
string(JSON _ock_header_count LENGTH "${_ock_installed_manifest}" headers)
math(EXPR _ock_header_last "${_ock_header_count}-1")
foreach(_ock_index RANGE ${_ock_header_last} 0 -1)
  string(JSON _ock_owner GET "${_ock_installed_manifest}" headers ${_ock_index} target)
  if(NOT _ock_owner IN_LIST _ock_installed_targets)
    string(JSON _ock_installed_manifest REMOVE "${_ock_installed_manifest}" headers ${_ock_index})
  endif()
endforeach()
# stage 表示同版 SDK 实现基线，installation_profile 表示本次实际安装裁剪。
string(JSON _ock_installed_manifest SET "${_ock_installed_manifest}" installation_profile "\"${OCK_BUILD_COMPONENTS}\"")
file(WRITE "${CMAKE_BINARY_DIR}/sdk_api_manifest.json" "${_ock_installed_manifest}\n")
install(FILES "${CMAKE_BINARY_DIR}/sdk_api_manifest.json" DESTINATION share/ock)
