# NativeSubset：Runtime 是生产静态库；其余未实施组件仍为合同目标。
function(ock_contract_target component include_root)
  string(REPLACE "::" "_" local_name "${component}")
  set(target "ock_${local_name}")
  add_library(${target} INTERFACE)
  add_library(OCK::${component} ALIAS ${target})
  set_target_properties(${target} PROPERTIES EXPORT_NAME "${component}" OCK_IMPLEMENTATION_STAGE ContractBaseline EXPORT_PROPERTIES OCK_IMPLEMENTATION_STAGE)
  target_compile_features(${target} INTERFACE cxx_std_20)
  target_compile_options(${target} INTERFACE "$<$<CXX_COMPILER_ID:MSVC>:/utf-8>")
  target_include_directories(${target} INTERFACE "$<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/${include_root}>" "$<INSTALL_INTERFACE:include>")
  foreach(dep IN LISTS ARGN)
    target_link_libraries(${target} INTERFACE OCK::${dep})
  endforeach()
  set_property(GLOBAL APPEND PROPERTY OCK_CONTRACT_TARGETS "${component}")
  install(TARGETS ${target} EXPORT OCKTargets)
endfunction()

ock_contract_target(Foundation packages/foundation/include)
set_target_properties(ock_Foundation PROPERTIES OCK_IMPLEMENTATION_STAGE Implemented)
target_link_libraries(ock_Foundation INTERFACE OCKThirdParty::expected)
target_compile_options(ock_Foundation INTERFACE "$<$<CXX_COMPILER_ID:MSVC>:/EHsc>" "$<$<CXX_COMPILER_ID:MSVC>:/Zc:__cplusplus>" "$<$<CXX_COMPILER_ID:MSVC>:/permissive->")
ock_contract_target(CoreContracts packages/contracts/include Foundation)
set_target_properties(ock_CoreContracts PROPERTIES OCK_IMPLEMENTATION_STAGE Implemented)
add_library(ock_Runtime STATIC
  "${PROJECT_SOURCE_DIR}/packages/runtime/registry/registry.cpp"
  "${PROJECT_SOURCE_DIR}/packages/runtime/policy/policy.cpp"
  "${PROJECT_SOURCE_DIR}/packages/runtime/invocation/invocation.cpp"
  "${PROJECT_SOURCE_DIR}/packages/runtime/host/host.cpp"
  "${PROJECT_SOURCE_DIR}/packages/runtime/scheduler/scheduler.cpp"
  "${PROJECT_SOURCE_DIR}/packages/runtime/resources/resources.cpp"
  "${PROJECT_SOURCE_DIR}/packages/runtime/executions/resource_wait_binding.cpp"
  "${PROJECT_SOURCE_DIR}/packages/runtime/executions/execution_identity.cpp"
  "${PROJECT_SOURCE_DIR}/packages/runtime/executions/host_execution.cpp"
  "${PROJECT_SOURCE_DIR}/packages/runtime/observability/logging.cpp")
add_library(OCK::Runtime ALIAS ock_Runtime)
set_target_properties(ock_Runtime PROPERTIES EXPORT_NAME Runtime OCK_IMPLEMENTATION_STAGE B5Subset EXPORT_PROPERTIES OCK_IMPLEMENTATION_STAGE)
target_link_libraries(ock_Runtime PUBLIC OCK::CoreContracts PRIVATE bcrypt)
target_compile_features(ock_Runtime PUBLIC cxx_std_20)
target_compile_options(ock_Runtime PUBLIC "$<$<CXX_COMPILER_ID:MSVC>:/utf-8>")
target_include_directories(ock_Runtime PUBLIC "$<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/packages/runtime/include>" "$<INSTALL_INTERFACE:include>" PRIVATE "${PROJECT_SOURCE_DIR}")
set_property(GLOBAL APPEND PROPERTY OCK_CONTRACT_TARGETS Runtime)
install(TARGETS ock_Runtime EXPORT OCKTargets ARCHIVE DESTINATION lib)
# 历史验证入口仅为同一生产库别名，不再编译第二份实现。
add_library(ock_registry_internal ALIAS ock_Runtime)
add_library(ock_policy_internal ALIAS ock_Runtime)
add_library(ock_invocation_internal ALIAS ock_Runtime)
# B2Subset 仅声明已接线的开发 SDK，不代表包级 Passed。
if(OCK_BUILD_B3)
function(ock_production_target component include_root)
  add_library(ock_${component} STATIC ${ARGN})
  add_library(OCK::${component} ALIAS ock_${component})
  set_target_properties(ock_${component} PROPERTIES EXPORT_NAME ${component} OCK_IMPLEMENTATION_STAGE B2Subset EXPORT_PROPERTIES OCK_IMPLEMENTATION_STAGE)
  target_compile_features(ock_${component} PUBLIC cxx_std_20)
  target_compile_options(ock_${component} PUBLIC "$<$<CXX_COMPILER_ID:MSVC>:/utf-8>")
  target_include_directories(ock_${component} PUBLIC "$<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/${include_root}>" "$<INSTALL_INTERFACE:include>" PRIVATE "${PROJECT_SOURCE_DIR}")
  set_property(GLOBAL APPEND PROPERTY OCK_CONTRACT_TARGETS ${component})
  install(TARGETS ock_${component} EXPORT OCKTargets ARCHIVE DESTINATION lib)
  install(DIRECTORY ${include_root}/ DESTINATION include)
endfunction()
if(NOT TARGET OCKThirdParty::jsoncons)
  message(FATAL_ERROR "B2 SDK requires the locked Data dependency component; select OCK_DEPENDENCY_COMPONENTS=Data")
endif()
ock_production_target(Data packages/dynamic/data/include packages/dynamic/data/payload.cpp)
target_link_libraries(ock_Data PUBLIC OCK::Foundation)
ock_production_target(Dynamic packages/dynamic/include packages/dynamic/binding/schema.cpp packages/dynamic/catalog/catalog.cpp)
target_link_libraries(ock_Dynamic PUBLIC OCK::Runtime OCK::Data PRIVATE bcrypt)
# jsoncons 仅供实现编译；静态库消费者无需 jsoncons 头或 CMake target。
foreach(component Data Dynamic)
  target_include_directories(ock_${component} SYSTEM PRIVATE "$<TARGET_PROPERTY:ock_dep_jsoncons,INTERFACE_INCLUDE_DIRECTORIES>")
  target_compile_definitions(ock_${component} PRIVATE "$<TARGET_PROPERTY:ock_dep_jsoncons,INTERFACE_COMPILE_DEFINITIONS>")
endforeach()
ock_contract_target(Automation packages/automation/include Runtime Dynamic)
ock_contract_target(State packages/state/include CoreContracts)
ock_contract_target(Workspace packages/workspace/include State)
ock_contract_target(Durable packages/durable/include CoreContracts)
ock_contract_target(StateDurable packages/bridges/state_durable/include State Durable)
ock_contract_target(DurablePlan packages/durable_plan/include Automation Durable)
ock_production_target(ControlProtocol packages/control/protocol/include
  packages/control/protocol/protocol.cpp packages/control/protocol/observation_wire.cpp packages/control/protocol/outcome_wire.cpp)
target_link_libraries(ock_ControlProtocol PUBLIC OCK::CoreContracts OCK::Data)
ock_production_target(Control packages/control/server/include
  packages/control/server/cursor.cpp packages/control/server/router.cpp packages/control/server/invoke_method.cpp packages/control/server/catalog_methods.cpp
  packages/control/observation/subscription.cpp packages/control/observation/subscription_methods.cpp packages/control/observation/list_method.cpp packages/control/observation/get_method.cpp
  packages/control/observation/observation_transport.cpp packages/control/observation/execution_method.cpp)
set_target_properties(ock_Control PROPERTIES OCK_IMPLEMENTATION_STAGE B5Subset)
target_link_libraries(ock_Control PUBLIC OCK::Runtime OCK::Dynamic OCK::ControlProtocol PRIVATE bcrypt)
if(OCK_BUILD_B3)
  ock_production_target(ControlClient packages/control/client/include packages/control/client/client.cpp packages/control/client/intent.cpp packages/control/client/watch.cpp)
  set_target_properties(ock_ControlClient PROPERTIES OCK_IMPLEMENTATION_STAGE B3Subset)
  target_link_libraries(ock_ControlClient PUBLIC OCK::ControlProtocol PRIVATE bcrypt)
else()
  ock_contract_target(ControlClient packages/control/client/include ControlProtocol)
endif()
if(NOT OCK_BUILD_CPU_POOL)
  ock_contract_target(Adapter::CpuPool packages/adapters/cpu_pool/include CoreContracts)
endif()
ock_contract_target(Adapter::Logging packages/adapters/logging/include CoreContracts)
ock_contract_target(Adapter::Config packages/adapters/config/include Dynamic)
ock_contract_target(Adapter::SQLite packages/adapters/sqlite/include Durable)
ock_contract_target(Adapter::Storage packages/adapters/storage/include CoreContracts)
if(OCK_BUILD_B3)
  if(NOT TARGET OCKThirdParty::asio)
    message(FATAL_ERROR "B3 requires the locked LocalIPC dependency component")
  endif()
  ock_production_target(Adapter_LocalIPC packages/adapters/local_ipc/include
    packages/adapters/local_ipc/native_security.cpp packages/adapters/local_ipc/pipe.cpp)
  add_library(OCK::Adapter::LocalIPC ALIAS ock_Adapter_LocalIPC)
  set_target_properties(ock_Adapter_LocalIPC PROPERTIES EXPORT_NAME Adapter::LocalIPC OCK_IMPLEMENTATION_STAGE B3Subset)
  get_property(_b3_components GLOBAL PROPERTY OCK_CONTRACT_TARGETS)
  list(REMOVE_ITEM _b3_components Adapter_LocalIPC)
  list(APPEND _b3_components Adapter::LocalIPC)
  set_property(GLOBAL PROPERTY OCK_CONTRACT_TARGETS "${_b3_components}")
  target_link_libraries(ock_Adapter_LocalIPC PUBLIC OCK::ControlProtocol PRIVATE advapi32)
  target_include_directories(ock_Adapter_LocalIPC SYSTEM PRIVATE "$<TARGET_PROPERTY:ock_dep_asio,INTERFACE_INCLUDE_DIRECTORIES>")
  target_compile_definitions(ock_Adapter_LocalIPC PRIVATE "$<TARGET_PROPERTY:ock_dep_asio,INTERFACE_COMPILE_DEFINITIONS>" _WIN32_WINNT=0x0A00)
else()
  ock_contract_target(Adapter::LocalIPC packages/adapters/local_ipc/include ControlProtocol)
endif()
ock_contract_target(Adapter::MCP packages/adapters/mcp/include Control)
endif()

if(OCK_BUILD_CPU_POOL)
  if(NOT TARGET OCKThirdParty::thread_pool)
    message(FATAL_ERROR "CpuPool requires locked OCK_DEPENDENCY_COMPONENTS to include CpuPool")
  endif()
  add_library(ock_Adapter_CpuPool STATIC packages/adapters/cpu_pool/executor.cpp)
  add_library(OCK::Adapter::CpuPool ALIAS ock_Adapter_CpuPool)
  set_target_properties(ock_Adapter_CpuPool PROPERTIES EXPORT_NAME Adapter::CpuPool OCK_IMPLEMENTATION_STAGE Implemented EXPORT_PROPERTIES OCK_IMPLEMENTATION_STAGE)
  target_link_libraries(ock_Adapter_CpuPool PUBLIC OCK::CoreContracts)
  target_compile_features(ock_Adapter_CpuPool PUBLIC cxx_std_20)
  target_compile_options(ock_Adapter_CpuPool PUBLIC "$<$<CXX_COMPILER_ID:MSVC>:/utf-8>")
  target_include_directories(ock_Adapter_CpuPool PUBLIC "$<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/packages/adapters/cpu_pool/include>" "$<INSTALL_INTERFACE:include>")
  target_include_directories(ock_Adapter_CpuPool SYSTEM PRIVATE "$<TARGET_PROPERTY:ock_dep_thread_pool,INTERFACE_INCLUDE_DIRECTORIES>")
  set_property(GLOBAL APPEND PROPERTY OCK_CONTRACT_TARGETS Adapter::CpuPool)
  install(TARGETS ock_Adapter_CpuPool EXPORT OCKTargets ARCHIVE DESTINATION lib)
  install(DIRECTORY packages/adapters/cpu_pool/include/ DESTINATION include)
endif()

function(ock_write_target_graph output)
  get_property(components GLOBAL PROPERTY OCK_CONTRACT_TARGETS)
  set(rows "")
  foreach(component IN LISTS components)
    string(REPLACE "::" "_" local_name "${component}")
    get_target_property(links ock_${local_name} INTERFACE_LINK_LIBRARIES)
    if(NOT links)
      set(links "")
    endif()
    get_target_property(kind ock_${local_name} TYPE)
    get_target_property(stage ock_${local_name} OCK_IMPLEMENTATION_STAGE)
    get_target_property(features ock_${local_name} INTERFACE_COMPILE_FEATURES)
    get_target_property(options ock_${local_name} INTERFACE_COMPILE_OPTIONS)
    get_target_property(definitions ock_${local_name} INTERFACE_COMPILE_DEFINITIONS)
    if(NOT definitions)
      set(definitions "")
    endif()
    set(definitions_rows "")
    foreach(definition IN LISTS definitions)
      list(APPEND definitions_rows "\"${definition}\"")
    endforeach()
    list(JOIN definitions_rows "," definitions_json)
    list(JOIN features "\",\"" features_json)
    list(JOIN options "\",\"" options_json)
    set(dependencies "")
    set(external_dependencies "")
    set(system_dependencies "")
    foreach(link IN LISTS links)
      if(link STREQUAL "$<LINK_ONLY:bcrypt>" AND (component STREQUAL "Runtime" OR component STREQUAL "Dynamic" OR component STREQUAL "Control" OR component STREQUAL "ControlClient"))
        list(APPEND system_dependencies "{\"name\":\"bcrypt\",\"platform\":\"Windows\",\"link_only\":true}")
      elseif(link STREQUAL "$<LINK_ONLY:advapi32>" AND component STREQUAL "Adapter::LocalIPC")
        list(APPEND system_dependencies "{\"name\":\"advapi32\",\"platform\":\"Windows\",\"link_only\":true}")
      elseif(link MATCHES "^OCKThirdParty::")
        string(REGEX REPLACE "^OCKThirdParty::" "" dependency "${link}")
        list(APPEND external_dependencies "\"${dependency}\"")
      else()
        # 未知链接继续进入待校验集合，禁止把未知依赖静默忽略。
        string(REGEX REPLACE "^OCK::" "" dependency "${link}")
        list(APPEND dependencies "\"${dependency}\"")
      endif()
    endforeach()
    list(JOIN system_dependencies "," system_dependencies_json)
    list(JOIN external_dependencies "," external_dependencies_json)
    list(JOIN dependencies "," dependencies_json)
    list(APPEND rows "\"${component}\": {\"kind\": \"${kind}\", \"system_dependencies\": [${system_dependencies_json}], \"dependencies\": [${dependencies_json}], \"external_dependencies\": [${external_dependencies_json}], \"implementation\": \"${stage}\", \"compile_features\": [\"${features_json}\"], \"compile_options\": [\"${options_json}\"], \"compile_definitions\": [${definitions_json}]}")
  endforeach()
  list(JOIN rows ",\n" rows_json)
  file(WRITE "${output}" "{\n\"format\":\"ock.cmake-target-graph/1\",\n\"build_components\":\"${OCK_BUILD_COMPONENTS}\",\n\"targets\":{\n${rows_json}\n}}\n")
endfunction()
