# NativeSubset：Runtime 是生产静态库；其余未实施组件仍为合同目标。
function(ock_contract_target component include_root)
  string(REPLACE "::" "_" local_name "${component}")
  set(target "ock_${local_name}")
  add_library(${target} INTERFACE)
  add_library(OCK::${component} ALIAS ${target})
  set_target_properties(${target} PROPERTIES EXPORT_NAME "${component}" OCK_IMPLEMENTATION_STAGE ContractBaseline EXPORT_PROPERTIES OCK_IMPLEMENTATION_STAGE)
  target_compile_features(${target} INTERFACE cxx_std_20)
  target_compile_options(${target} INTERFACE "$<$<CXX_COMPILER_ID:MSVC>:/utf-8>")
  target_include_directories(${target} INTERFACE "$<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/${include_root}>" "$<INSTALL_INTERFACE:include>")
  foreach(dep IN LISTS ARGN)
    target_link_libraries(${target} INTERFACE OCK::${dep})
  endforeach()
  set_property(GLOBAL APPEND PROPERTY OCK_CONTRACT_TARGETS "${component}")
  install(TARGETS ${target} EXPORT OCKTargets)
endfunction()

ock_contract_target(Foundation packages/foundation/include)
set_target_properties(ock_Foundation PROPERTIES OCK_IMPLEMENTATION_STAGE Implemented)
target_link_libraries(ock_Foundation INTERFACE OCKThirdParty::expected)
target_compile_options(ock_Foundation INTERFACE "$<$<CXX_COMPILER_ID:MSVC>:/EHsc>" "$<$<CXX_COMPILER_ID:MSVC>:/Zc:__cplusplus>" "$<$<CXX_COMPILER_ID:MSVC>:/permissive->")
ock_contract_target(CoreContracts packages/contracts/include Foundation)
set_target_properties(ock_CoreContracts PROPERTIES OCK_IMPLEMENTATION_STAGE Implemented)
add_library(ock_Runtime STATIC
  "${PROJECT_SOURCE_DIR}/packages/runtime/registry/registry.cpp"
  "${PROJECT_SOURCE_DIR}/packages/runtime/policy/policy.cpp"
  "${PROJECT_SOURCE_DIR}/packages/runtime/invocation/invocation.cpp"
  "${PROJECT_SOURCE_DIR}/packages/runtime/host/host.cpp"
  "${PROJECT_SOURCE_DIR}/packages/runtime/observability/logging.cpp")
add_library(OCK::Runtime ALIAS ock_Runtime)
set_target_properties(ock_Runtime PROPERTIES EXPORT_NAME Runtime OCK_IMPLEMENTATION_STAGE NativeSubset EXPORT_PROPERTIES OCK_IMPLEMENTATION_STAGE)
target_link_libraries(ock_Runtime PUBLIC OCK::CoreContracts PRIVATE bcrypt)
target_compile_features(ock_Runtime PUBLIC cxx_std_20)
target_compile_options(ock_Runtime PUBLIC "$<$<CXX_COMPILER_ID:MSVC>:/utf-8>")
target_include_directories(ock_Runtime PUBLIC "$<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/packages/runtime/include>" "$<INSTALL_INTERFACE:include>" PRIVATE "${PROJECT_SOURCE_DIR}")
set_property(GLOBAL APPEND PROPERTY OCK_CONTRACT_TARGETS Runtime)
install(TARGETS ock_Runtime EXPORT OCKTargets ARCHIVE DESTINATION lib)
# 历史验证入口仅为同一生产库别名，不再编译第二份实现。
add_library(ock_registry_internal ALIAS ock_Runtime)
add_library(ock_policy_internal ALIAS ock_Runtime)
add_library(ock_invocation_internal ALIAS ock_Runtime)
ock_contract_target(Data packages/data/include Foundation)
ock_contract_target(Dynamic packages/dynamic/include Runtime Data)
ock_contract_target(Automation packages/automation/include Runtime Dynamic)
ock_contract_target(State packages/state/include CoreContracts)
ock_contract_target(Workspace packages/workspace/include State)
ock_contract_target(Durable packages/durable/include CoreContracts)
ock_contract_target(StateDurable packages/bridges/state_durable/include State Durable)
ock_contract_target(DurablePlan packages/durable_plan/include Automation Durable)
ock_contract_target(ControlProtocol packages/control/protocol/include CoreContracts Data)
ock_contract_target(Control packages/control/server/include Runtime Dynamic ControlProtocol)
ock_contract_target(ControlClient packages/control/client/include ControlProtocol)
ock_contract_target(Adapter::CpuPool packages/adapters/cpu_pool/include CoreContracts)
ock_contract_target(Adapter::Logging packages/adapters/logging/include CoreContracts)
ock_contract_target(Adapter::Config packages/adapters/config/include Dynamic)
ock_contract_target(Adapter::SQLite packages/adapters/sqlite/include Durable)
ock_contract_target(Adapter::Storage packages/adapters/storage/include CoreContracts)
ock_contract_target(Adapter::LocalIPC packages/adapters/local_ipc/include ControlProtocol)
ock_contract_target(Adapter::MCP packages/adapters/mcp/include Control)

function(ock_write_target_graph output)
  get_property(components GLOBAL PROPERTY OCK_CONTRACT_TARGETS)
  set(rows "")
  foreach(component IN LISTS components)
    string(REPLACE "::" "_" local_name "${component}")
    get_target_property(links ock_${local_name} INTERFACE_LINK_LIBRARIES)
    if(NOT links)
      set(links "")
    endif()
    get_target_property(kind ock_${local_name} TYPE)
    get_target_property(stage ock_${local_name} OCK_IMPLEMENTATION_STAGE)
    get_target_property(features ock_${local_name} INTERFACE_COMPILE_FEATURES)
    get_target_property(options ock_${local_name} INTERFACE_COMPILE_OPTIONS)
    get_target_property(definitions ock_${local_name} INTERFACE_COMPILE_DEFINITIONS)
    if(NOT definitions)
      set(definitions "")
    endif()
    set(definitions_rows "")
    foreach(definition IN LISTS definitions)
      list(APPEND definitions_rows "\"${definition}\"")
    endforeach()
    list(JOIN definitions_rows "," definitions_json)
    list(JOIN features "\",\"" features_json)
    list(JOIN options "\",\"" options_json)
    set(dependencies "")
    set(external_dependencies "")
    set(system_dependencies "")
    foreach(link IN LISTS links)
      if(link STREQUAL "$<LINK_ONLY:bcrypt>" AND component STREQUAL "Runtime")
        list(APPEND system_dependencies "{\"name\":\"bcrypt\",\"platform\":\"Windows\",\"link_only\":true}")
      elseif(link MATCHES "^OCKThirdParty::")
        string(REGEX REPLACE "^OCKThirdParty::" "" dependency "${link}")
        list(APPEND external_dependencies "\"${dependency}\"")
      else()
        # 未知链接继续进入待校验集合，禁止把未知依赖静默忽略。
        string(REGEX REPLACE "^OCK::" "" dependency "${link}")
        list(APPEND dependencies "\"${dependency}\"")
      endif()
    endforeach()
    list(JOIN system_dependencies "," system_dependencies_json)
    list(JOIN external_dependencies "," external_dependencies_json)
    list(JOIN dependencies "," dependencies_json)
    list(APPEND rows "\"${component}\": {\"kind\": \"${kind}\", \"system_dependencies\": [${system_dependencies_json}], \"dependencies\": [${dependencies_json}], \"external_dependencies\": [${external_dependencies_json}], \"implementation\": \"${stage}\", \"compile_features\": [\"${features_json}\"], \"compile_options\": [\"${options_json}\"], \"compile_definitions\": [${definitions_json}]}")
  endforeach()
  list(JOIN rows ",\n" rows_json)
  file(WRITE "${output}" "{\n\"format\":\"ock.cmake-target-graph/1\",\n\"targets\":{\n${rows_json}\n}}\n")
endfunction()
